export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_DOGS_PENDING = "REQUEST_DOGS_PENDING";
export const REQUEST_DOGS_SUCCESS = "REQUEST_DOGS_SUCCESS";
export const REQUEST_DOGS_FAILED = "REQUEST_DOGS_FAILED";
